AllCops:
  Exclude:
    - 'test/**/*'
    - 'vendor/bundle/**/*'
  RunRailsCops: true

Metrics/AbcSize:
  Max: 42.73 # TODO: Lower to 15

#Metrics/ClassLength:
#  CountComments: false
#  Max: 120 # TODO: Lower to 100

Metrics/CyclomaticComplexity:
  Max: 10 # TODO: Lower to 6

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 24

Metrics/ModuleLength:
  Max: 131 # TODO: Lower to 100

Metrics/ParameterLists:
  Max: 8 # TODO: Lower to 5

Metrics/PerceivedComplexity:
  Max: 11 # TODO: Lower to 7

Style/Documentation:
  Enabled: false

Style/SpaceAroundOperators:
  MultiSpaceAllowedForOperators:
    - '='
    - '=>'
    - '||='

Style/UnneededPercentQ:
  Exclude:
    - 'route_translator.gemspec'
